# Generated by Django 4.0 on 2022-03-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matches',
            fields=[
                ('match_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('team_1_name', models.CharField(max_length=30)),
                ('team_2_name', models.CharField(max_length=30)),
                ('winner', models.CharField(max_length=30)),
                ('loser', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=30)),
                ('umpire_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=200)),
                ('batting_average', models.IntegerField()),
                ('no_of_totalruns', models.IntegerField()),
                ('no_of_wickets', models.IntegerField()),
                ('type_of_bowler', models.CharField(max_length=30)),
                ('economy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='umpire',
            fields=[
                ('umpire_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('umpire_name', models.CharField(max_length=30)),
                ('no_of_matches', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_rank', models.IntegerField()),
                ('team_name', models.CharField(max_length=20)),
                ('no_of_wins', models.IntegerField()),
                ('no_of_loses', models.IntegerField()),
                ('no_of_bowlers', models.IntegerField()),
                ('no_of_batsmen', models.IntegerField()),
                ('has', models.ManyToManyField(to='CRICKET_APP.player')),
                ('plays', models.ManyToManyField(to='CRICKET_APP.matches')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='umpired_by',
            field=models.ManyToManyField(to='CRICKET_APP.umpire'),
        ),
        migrations.CreateModel(
            name='captain',
            fields=[
                ('captain_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('captain_name', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=20)),
                ('leads', models.ManyToManyField(to='CRICKET_APP.team')),
            ],
        ),
    ]
