# Generated by Django 4.0 on 2022-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRICKET_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
