# Generated by Django 4.0 on 2022-03-22 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRICKET_APP', '0002_team_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='match_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
