# Generated by Django 4.0.1 on 2022-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRICKET_APP', '0003_team_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_average',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='economy',
            field=models.FloatField(),
        ),
    ]
