# Generated by Django 4.0.1 on 2022-03-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRICKET_APP', '0004_alter_player_batting_average_alter_player_economy'),
    ]

    operations = [
        migrations.CreateModel(
            name='sam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs', models.CharField(max_length=10)),
                ('ks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRICKET_APP.player')),
            ],
        ),
    ]
