# Generated by Django 4.0.1 on 2022-03-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRICKET_APP', '0005_sam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sam',
        ),
    ]
